### ISSUE TITLE
[Request] Doctrines and Payout Percentages

### ISSUE THREAD

**Issue by epoch18** [ppfeufer/aa-srp#36]
### Context

Add more granularity to doctrines. Custom set payout amounts. ESI verified payments. Discord notifications. 

My idea covers a few areas that I think would be a helpful improvement. Not only for more features, but ease of use and hopefully quicker processing. 

### Describe the feature you have in mind

Doctrines:
This could be done several ways, I'm sure, but my thought is "Doctrine" would be a new item (instead of just a free-form field). At it's simplest, a "Doctrine" (or maybe "Ship Doctrine" or "Doctrine Fitting" for clarity) could be a free-form name, and a long text description field (could past the fit in this field, just for reference). An "active" checkbox (or "inactive" whichever makes more sense). Also, there would be a payout for this doctrine ship/fit specifically, as a percentage (default to 100%). So the SRP payout amount would change based on this percentage. If the killmail is 100 mil and it's set to 90%, then the payout would be 90 mil. 

Context: (For my corp/alliance) Some ship types/fits pay more. Some less. Example, logi ships get paid out at 150% or 200%. Yes, we _pay_ people to fly logi. 

New item: "Fleet Doctrine". 
A "Fleet Doctrine" is a group _active_ of "Ship Doctrines", chosen from some type of muti-select field. Name field, optional description field because why not. And that's pretty much all it needs to be (I think). Also an "active" checkbox (or "inactive" whichever makes more sense). 

Change to SRP Link creation: 
"Fleet Doctrine" field would now be a drop down list of the available _active_ Fleet Doctrines. Also, add a payout for this fleet. So this percentage would be combined with the fit payout percentage. 
_Ex1: ((Killmail Value: 100 mil) * (Fitting%: 0.90)) * (SRP Link%: 75%) = SRP Payout: 67.5 mil._
_Ex2: ((Killmail Value: 100 mil) * (Fitting%: 1.50)) * (SRP Link%: 75%) = SRP Payout: 112.5 mil._

Context: More important fleets get more payout. Or, more specifically, small shit fleets get paid less. Strat ops and CTAs get 100%. Regular pinged fleets get 75%. Random/fuck around fleets get 50%. 

_(The following changes could be separate from the granular doctrine changes above. If done separately, I would still request at least the new Payout % field/functionality on just the SRP Link Creation.)_

Change to SRP Requests view/template: 
Add "ISK Payout" next to "ISK Lost" column. "ISK" Payout" is the calculated value from above (67.5 mil from the example). 
Add a "Copy to clipboard" icon/link for the "ISK Payout" field. This speeds up the actual in-game payout process, and reduces 
human errors. 
Add a "Copy to clipboard" icon/link for the "Request Code" field. This speeds up the actual in-game payout process, and reduces human errors, related to the Discord Functionality change below. Prepend "SRP: " to the code for easier identification in the wallet transaction "Reason" field in game. 

New status and icon for SRP requests: 
Scan Corp Wallet ESI data for wallet transactions with the Reason field containing a matching Request Code. If found, change SRP request to "Paid" status and add "Paid" icon. 

Context: Anyone can simply press the "accept" button, but that does not mean the member has been paid. This adds a level of verification to ensure nothing is lost or forgotten. 

New Discord functionality:
Add a new message type to be sent to Discord when a user has been paid. Ideally the message would contain the person who made the payment as well. 

### Additional context

I think that's it. Hopefully I was able to make myself clear. If not, I can make a bunch of mockups and flow charts to help.

**Comment by ppfeufer** [comment]
Thank you for this detailed request.

Regarding the changes to the payment calculation you detailed, I have to decline. You explained how _your_ alliance is calculating things. So this change would _only_ benefit your alliance. Now there are a couple more alliances out there, and they all have their own way of calculating the payout. My corp for example just hands fitted ships out as SRP. The alliance I'm in has a very complicated method in place that I don't even try to understand. Others check the fittings and factor in changed modules, like Meta 4 instead of T2 => 10% less payout ... and so on.

So any changes to the payout calculation will only benefit 1 or 2 alliances/corps that do it the same way. This is why I leave it completely to the corp/alliance using this tool to calculate their own payout but give them the ability to enter the payout value, for a little statistic for each SRP link.

As for the ESI wallet checks, it is a similar problem I'm facing. Not every corp/alliance is paying in ISK, some are just handing out ships (fitted or not doesn't matter here). So all I can do with an ESI wallet check is to have it as a kind of optional sanity check. I am playing with it in my head since you mentioned it in Discord, and I can't think of a reliable way to implement it for it being more than just an optional sanity check. For example, I have no reliable way to detect the actual payment. It has to be **only** the SRP Request Code in the payments subject field, nothing else for that to happen. And we both know how fast people f**k that up :-)

So yes, as a sanity check, I might implement this at some point.

**Comment by ppfeufer** [comment]
I'm just leaving this here for reference

```
/corporations/{corporation_id}/divisions/
esi-corporations.read_divisions.v1
```

```
/corporations/{corporation_id}/wallets/{division}/journal/
esi-wallet.read_corporation_wallets.v1
```

**Comment by epoch18** [comment]
`So any changes to the payout calculation will only benefit 1 or 2 alliances/corps that do it the same way.`

But if you keep making changes that includes a few more alliances at a time, you'll eventually get them all! lol. 

Seriously though, I have already though of ways to add _way_ more functionality for SRP and all sorts of various ways to do it. That's my RL job (Product Manager). I just don't have the ability to code it. :(
