### ISSUE TITLE
[Feature Request] Set Pre-Determined Payouts

### ISSUE THREAD

**Issue by paintballlaws** [ppfeufer/aa-srp#54]
### Context

The ability to have a preset payout amount for a specific ship.

### Describe the feature you have in mind

Basically have a table that has a pre-determined amount for a ship SRP based on what type of fleet it is and then when a SRP person clicks on the SRP payout amount it opens a small window with buttons for those different payout options.

### Additional context
Here is small preview of something that I'm talking about
![image](https://user-images.githubusercontent.com/2366416/155774279-76dc7cd9-9bcb-4bc3-b5e9-1f9584de10a3.png)

**Comment by ppfeufer** [comment]
Sorry but no.

Every entity has its own way of calculating payouts and I am not starting to implement this, because that caters to your way of calculating, not others and I would have to do that for potentially countless alliances and corporations. This will definitely be out of scope here, so you have to do the math manually.
