### ISSUE TITLE
[Feature Request] Using in-game killmail link

### ISSUE THREAD

**Issue by paintballlaws** [ppfeufer/aa-srp#55]
### Context

Ability to use in-game killmail link instead of zkill or kb.tools

**Comment by ppfeufer** [comment]
Have to decline here as well for now. This would not generate a kill mail link which is nice to have for the SRP guys to check. I also would have to re-invent the wheel for parsing kill mails from ESI, which already has been done by zKillboard. It would also slow down the initial processing of SRP requests a lot and rely too much on ESI not shitting the bed while fetching all data. Too many points of potential errors are involved.

Maybe one day when CCP manages to make sure ESI is actually a stable and usable service ... but then there is still the issue of not having a kill mail link. And as far as I know, zKillboard's API does not support posting ESI kill mail links to get the zKillboard link for the kill mail.

**Comment by ppfeufer** [comment]
After a year there is still no change that would make this possible.
Closing.

**Comment by crius-al** [comment]
> Have to decline here as well for now. This would not generate a kill mail link which is nice to have for the SRP guys to check. I also would have to re-invent the wheel for parsing kill mails from ESI, which already has been done by zKillboard. It would also slow down the initial processing of SRP requests a lot and rely too much on ESI not shitting the bed while fetching all data. Too many points of potential errors are involved.
> 
> Maybe one day when CCP manages to make sure ESI is actually a stable and usable service ... but then there is still the issue of not having a kill mail link. And as far as I know, zKillboard's API does not support posting ESI kill mail links to get the zKillboard link for the kill mail.
> 
> I'll leave this one open in case something changes that might make this possible.

Why reinvent the wheel when we have the zkillboard source code at https://github.com/zKillboard/zKillboard ?

**Comment by crius-al** [comment]
> After a year there is still no change that would make this possible. Closing.



> After a year there is still no change that would make this possible. Closing.

Based on my reading of the zkillboard comments, where it says:
```
Installation

This is a set of code that is beta and is constantly in flux. Which means it is a work in progress. It lacks complete documentation and is currently not meant for use by those who do not have a lot of experience in setting up PHP, TokuDB (a derivative of MongoDB), and Redis. Please feel free to attempt to install zKillboard on your own server, however, we are not responsible for any difficulties you come across during installation and continuing execution.
```
it would be possible to run zkillboard on a private server (on the client's machine), and to submit the links via' this method which would hide the kills from the public server, and still allow zkillboard to do all the parsing. All that would need to be done is to accept a custom URL and run the zkillboard on that URL instead.

A few people are worried about having to post all our killmails to a public server in order to SRP them, and this would probably solve the problem.

**Comment by ppfeufer** [comment]
Now you're starting a completely different topic.

I also won't support self-hosted zkillboard instances, because that would mean I have to instalö it myself to test, which I will not do.

Bottom line(s):
- Parsing ESI killmails would mean I have to implement a complete killmail parser, which is a lot of work for something that is likely to not give me a killmail link back in return, which is needed by the module.
- zkillboard's API doesn't support me throwing ESI killmail links at it and getting a killmail link in return.
- Selh-hosted zkillboard instances are a completely different kind of beast and are not supported by this module, and the chances they ever will be is next to nothing.

Or in short:
The module needs a link to a killmail from one of the 2 supported killboard systems. This will not change. And methods that won't produce such a link are not supported. 
I am sorry.

**Comment by crius-al** [comment]
> 

Thank you for this explanation. I will tell my alliance. Be well.
